title: "K's Website" # your name (or website title) here
logo: "/images/scout.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  やっほ～! I am a general software developer interested in employment.
  <br><br>
  I am a quick learner and willing to learn just about any software or code language necessary to do my task.
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
